language: android
android:
  components:
    - platform-tools-23.0.1
    - build-tools-23.0.1
    - android-23
    - sys-img-armeabi-v7a-android-21
    - extra-android-m2repository

env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest